version: "2"
services:
  mail-stats-frontend:
    image: rabblerouser/mail-stats-frontend
    build: "git@github.com:rabblerouser/mail-stats.git#:frontend"
    ports:
      - "8181:8181"
    environment:
      PORT: 8181
    command: yarn start
    labels:
      io.fdy.cage.srcdir: "/app"
      io.fdy.cage.test: "yarn test"

  mail-stats:
    image: rabblerouser/mail-stats
    build: "git@github.com:rabblerouser/mail-stats.git#:backend"
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      LISTENER_AUTH_TOKEN: secret
    external_links:
      - "s3:rr-event-archive.s3"
      - "s3:email-bucket.s3"
    command: yarn dev
    labels:
      io.fdy.cage.srcdir: "/app"
      io.fdy.cage.test: "yarn test"
      io.fdy.cage.lib.stream_client: "/app/backend/node_modules/@rabblerouser/stream-client"

  mail-stats-event-forwarder:
    image: rabblerouser/event-forwarder
    build: "git@github.com:rabblerouser/event-forwarder.git"
    environment:
      LISTENER_ENDPOINT: http://mail-stats:3003/events
      LISTENER_AUTH_TOKEN: secret
    labels:
      io.fdy.cage.srcdir: "/app"
      io.fdy.cage.test: "yarn test"
